version: '2'
services:

  db:
    env_file:
        - docker/postgres/db.env
    image: "postgres:9.4"
    expose:
        - 5432

  buildbot:
    build: docker/buildbot-master
    env_file:
        - docker/postgres/db.env
    environment:
        - BUILDBOT_CONFIG_DIR=config
    links:
        - db
    depends_on:
        - db
    ports:
        - "8080:8080"
    expose:
        - 8080
    volumes:
        - ./:/usr/src/app

  web:
    build:
        context: .
        dockerfile: ./docker/nginx/Dockerfile
    ports:
        - "80:8080"
    links:
        - buildbot

  worker:
    build: docker/buildbot-worker
    depends_on:
        - buildbot
    environment:
        BUILDMASTER: buildbot
        BUILDMASTER_PORT: 9989
        WORKERNAME: example-worker
        WORKERPASS: pass
        WORKER_ENVIRONMENT_BLACKLIST: DOCKER_BUILDBOT* BUILDBOT_ENV_* BUILDBOT_1* WORKER_ENVIRONMENT_BLACKLIST
    links:
        - buildbot
