version: '2'
services:
#    qemu_x86_64: 
#        build: .
#        command: ./tools/harness/runtests.py && mv ./results $CIRCLE_ARTIFACTS

    gem5_armv7:
        build:
          context: .
          dockerfile: Dockerfile.gem5
        command: bash -c "./tools/harness/runtests.py -f tools/harness/testlist/gem5_armv7.test -m armv7_gem5 ; ls ; echo $CIRCLE_ARTIFACTS ; ls $CIRCLE_ARTIFACTS ; mv ./results $CIRCLE_ARTIFACTS ; ls ; ls $CIRCLE_ARTIFACTS"
