version: '2'
services:
    qemu_x86_64: 
        build:
          context: .
          dockerfile: docker/x86_64_qemu/Dockerfile
        command: ./tools/harness/runtests.py

    gem5_armv7:
        build:
          context: .
          dockerfile: docker/armv7_gem5/Dockerfile
        command: ./tools/harness/runtests.py -f tools/harness/testlist/gem5_armv7.test -m armv7_gem5

    mips_sys161:
        build:
          context: .
          dockerfile: docker/mips_sys161/Dockerfile
        command: ../hake/hake.sh -s .. -a mips > $CIRCLE_ARTIFACTS/hakelog.out 2> $CIRCLE_ARTIFACTS/hakelog.err
