version: '2'
services:
    qemu_x86_64: 
        build: .
        command: ./tools/harness/runtests.py

    gem5_armv7:
        build:
          context: .
          dockerfile: Dockerfile.gem5
        command: ./tools/harness/runtests.py -f tools/harness/testlist/gem5_armv7.test -m armv7_gem5
