OCAMLMAKEFILE = ../OCamlMakefile

SOURCES = types.ml util.ml pos.ml \
	parsetree.ml parsecheck.mli parsecheck.ml \
	parser.mly lexer.mll \
	hamparser.ml
RESULT  = hamparser
THREADS = yes

include $(OCAMLMAKEFILE)
