# temporary scaffolding

include base.mk

PROG=hamparser
SRCS=types.ml util.ml pos.ml \
	hamlet/parsetree.ml hamlet/parsecheck.mli hamlet/parsecheck.ml \
	hamlet/parser.mly hamlet/lexer.mll \
	hamlet/hamparser.ml

include ocaml.mk
